name = livingfloatlands
description = Adds extra prehistoric biomes (without replacing vanilla ones) and low-lag prehistoric animals in matching climates.
depends = mobs, default, doors
optional_depends = animalworld, ethereal, farming, hunger_ng, bonemeal, livingdesert
